#!/bin/sh -e

vcs '-full64' '-timescale=1ns/1ps' '-debug_access+r' '-j80' '-lca' '-o' 'simv' '-top' 'fp_testbench' '-debug_all' '-liblist' 'WORK' "-lca" "-makedepends=Makefile.VCSMX_FOR_DVE_REBUILD"
gmake -f Makefile.VCSMX_FOR_DVE_REBUILD
vcs '-full64' '-timescale=1ns/1ps' '-debug_access+r' '-j80' '-lca' '-o' 'simv' '-top' 'fp_testbench' '-debug_all' '-liblist' 'WORK'
